import type { CampaignBrief } from './types'

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`

/** Seed marketplace briefs with real cover photos */
export const MOCK_BRIEFS: CampaignBrief[] = [
  {
    id: 'mock-cocoarush',
    source: 'mock',
    title: 'CocoaRush Launch',
    brandName: 'CocoaRush',
    description:
      'Launch our ready-to-drink cocoa in Accra. Show a natural morning ritual — pour, sip, smile.',
    campaignType: 'Product launch',
    category: 'Food',
    budgetUsdc: 500,
    minViews: 50000,
    durationDays: 7,
    platforms: ['TikTok', 'Instagram'],
    deliverables: '2 short videos (15–30s) + 1 story series',
    hashtags: '#CocoaRush #MadeInGhana #MorningFuel',
    wantStyle: 'Warm, sunny, lifestyle. Close-ups of the drink, friends vibes, upbeat audio.',
    avoidStyle: 'No hospital/medical claims. No competing drink brands in frame.',
    talkingPoints: 'Local cocoa · natural energy · affordable everyday treat',
    dos: 'Show the bottle label clearly · Tag @cocoarushgh',
    donts: 'No alcohol · No political content',
    coverImage: img('photo-1511920170033-f8396924c348'),
    assetImages: [
      img('photo-1495474472287-4d71bcdd2085'),
      img('photo-1571934811356-5cc061b6821f'),
    ],
    status: 'live',
    selectionMode: 'open',
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'mock-datapadi',
    source: 'mock',
    title: 'DataPadi Bundle Push',
    brandName: 'DataPadi',
    description: 'Explain the new student data bundle in under 30 seconds.',
    campaignType: 'App install',
    category: 'Tech',
    budgetUsdc: 200,
    minViews: 25000,
    durationDays: 5,
    platforms: ['TikTok', 'YouTube'],
    deliverables: '1 talking-head explainer + screen recording of the app',
    hashtags: '#DataPadi #StudentData #AccraTech',
    wantStyle: 'Clear, educational, energetic. Show the app UI.',
    avoidStyle: 'No fake “unlimited” promises. No competitor logos.',
    talkingPoints: 'Student price · easy top-up · works nationwide',
    dos: 'Show download CTA · Use provided end-card',
    donts: 'No spammy giveaway lies',
    coverImage: img('photo-1551650975-87deedd944c3'),
    assetImages: [img('photo-1512941937669-90a1b58e7e9c')],
    status: 'funded',
    selectionMode: 'open',
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'mock-accra-fit',
    source: 'mock',
    title: 'AccraFit Challenge',
    brandName: 'AccraFit',
    description: '7-day morning workout teasers filmed outdoors in Accra.',
    campaignType: 'Brand awareness',
    category: 'Lifestyle',
    budgetUsdc: 350,
    minViews: 40000,
    durationDays: 10,
    platforms: ['Instagram', 'TikTok'],
    deliverables: '3 workout clips + 1 before/after story',
    hashtags: '#AccraFit #MoveAccra',
    wantStyle: 'Sweaty, authentic, motivating. Golden-hour light preferred.',
    avoidStyle: 'No body-shaming. No unsafe form demos.',
    talkingPoints: 'Community classes · first week free trial',
    dos: 'Wear AccraFit tee if provided · Tag location',
    donts: 'No supplement medical claims',
    coverImage: img('photo-1571019614242-c5c5dee9f50b'),
    assetImages: [img('photo-1517836357463-d25dfeac3438')],
    status: 'live',
    selectionMode: 'open',
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'mock-sika-bank',
    source: 'mock',
    title: 'SikaBank Youth Card',
    brandName: 'SikaBank',
    description: 'Friendly explainers for first-time debit card users (18–25).',
    campaignType: 'Education series',
    category: 'Finance',
    budgetUsdc: 800,
    minViews: 100000,
    durationDays: 14,
    platforms: ['YouTube', 'TikTok', 'Instagram'],
    deliverables: '1 long-form tip video OR 3 short tips',
    hashtags: '#SikaBank #YouthCard #SmartMoney',
    wantStyle: 'Trustworthy, simple language, clean backgrounds.',
    avoidStyle: 'No get-rich-quick. No crypto speculation.',
    talkingPoints: 'Zero monthly fee · instant alerts · student perks',
    dos: 'Disclose paid partnership · Use official card mock visuals only',
    donts: 'Do not share real card numbers',
    coverImage: img('photo-1563013544-824ae9b996cb'),
    assetImages: [img('photo-1554224155-6726b3ff858f')],
    status: 'live',
    selectionMode: 'open',
    createdAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'mock-kente-drop',
    source: 'mock',
    title: 'KenteDrop Lookbook',
    brandName: 'KenteDrop',
    description: 'Fashion try-on and styling tips for the new capsule collection.',
    campaignType: 'Product launch',
    category: 'Fashion',
    budgetUsdc: 450,
    minViews: 60000,
    durationDays: 7,
    platforms: ['Instagram', 'TikTok'],
    deliverables: '1 lookbook reel + 2 styling tips',
    hashtags: '#KenteDrop #AfroLuxury',
    wantStyle: 'Editorial, colorful, confident walks / fits.',
    avoidStyle: 'No low-light blurry fits. No knockoff comparisons.',
    talkingPoints: 'Handwoven details · limited drop · Accra pickup',
    dos: 'Tag product SKUs in caption',
    donts: 'No resale / unauthorized discount codes',
    coverImage: img('photo-1483985988355-763728e1935b'),
    assetImages: [img('photo-1469334031218-e382a71b716b')],
    status: 'submitted',
    selectionMode: 'open',
    createdAt: Date.now() - 86400000 * 5,
  },
  {
    id: 'mock-learnlab',
    source: 'mock',
    title: 'LearnLab STEM Week',
    brandName: 'LearnLab',
    description: 'Cover free coding workshops happening in Accra this week.',
    campaignType: 'Event promo',
    category: 'Education',
    budgetUsdc: 300,
    minViews: 20000,
    durationDays: 7,
    platforms: ['TikTok', 'X'],
    deliverables: '2 event highlight clips',
    hashtags: '#LearnLab #STEMAccra',
    wantStyle: 'Curious students, laptops, whiteboard moments.',
    avoidStyle: 'No classroom disruption. No filming minors without consent.',
    talkingPoints: 'Free seats · register link in bio',
    dos: 'Show QR / link sticker',
    donts: 'No paid course upsells for other brands',
    coverImage: img('photo-1509062522246-3755977927d7'),
    assetImages: [img('photo-1516321318423-f06f85e504b3')],
    status: 'live',
    selectionMode: 'open',
    createdAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'mock-gamegate',
    source: 'mock',
    title: 'GameGate Tournament',
    brandName: 'GameGate',
    description: 'Gaming creators clip highlights from the weekend cup.',
    campaignType: 'Event promo',
    category: 'Gaming',
    budgetUsdc: 600,
    minViews: 80000,
    durationDays: 4,
    platforms: ['YouTube', 'TikTok'],
    deliverables: '1 highlight montage (30–60s)',
    hashtags: '#GameGate #AccraEsports',
    wantStyle: 'High energy, game audio OK with voiceover.',
    avoidStyle: 'No toxic chat overlays. No piracy talk.',
    talkingPoints: 'Prize pool · watch party locations',
    dos: 'Use official intro sting (asset pack)',
    donts: 'No gambling promotion',
    coverImage: img('photo-1542751371-adc38448a05e'),
    assetImages: [img('photo-1511512578047-dfb367046420')],
    status: 'funded',
    selectionMode: 'open',
    createdAt: Date.now() - 86400000 * 2,
  },
]

export function getMockBrief(id: string): CampaignBrief | undefined {
  return MOCK_BRIEFS.find((c) => c.id === id)
}
